In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# always rows by columns
arr = np.arange(10)
print(arr)
arr.shape

[0 1 2 3 4 5 6 7 8 9]


(10,)

In [4]:
arr = arr.reshape(2,5)
print(arr)
# arr.reshape(#, #, -1) whereas -1 indicates letting reshape function to figure out 
# the 3rd dimension
# https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
arr = np.full(10, np.nan)
print(arr)
arr[0:8] = 1
print(arr)

[nan nan nan nan nan nan nan nan nan nan]
[ 1.  1.  1.  1.  1.  1.  1.  1. nan nan]


inspace vs arange
linspace specify end points